######################################
# Procurement Service Config         #
######################################

# Apollo STOMP Broker Configuration
stompQueueName: /queue/26642.book.orders
stompQueuePrefix: /queue/26642.book.

# Procurement Service needs to publish to all topics!
stompTopicPrefix: /topic/26642.book.

apolloUser: "admin"
apolloPassword: "password"
#Y
apolloHost: "54.193.56.218"
#X
#apolloHost: "54.215.133.131"
apolloPort: 61613

#id for procurement scheduler
procurementId: 26642

#publisher resource address
publisherResource: "http://54.193.56.218:9000/orders/26642"

# HTTP-specific options.
http:
  # Root Path http://{host}:{port}/xxx
  rootPath: /*

  # The port on which the HTTP server listens for service requests.
  port: 9090

  # The port on which the HTTP server listens for administrative requests.
  adminPort: 9000


httpClient:
  # The broker does not support gzip encoding. Disabling it...
  gzipEnabled: false
  gzipEnabledForRequests: false


# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'edu.sjsu.cmpe' to DEBUG.
    edu.sjsu.cmpe: DEBUG

  # Settings for logging to stdout.
  console:

    # If true, write log statements to stdout.
    enabled: true

    # Do not display log statements below this threshold to stdout.
    threshold: ALL

  # Settings for logging to a file.
  file:

    # If true, write log statements to a file.
    enabled: true

    # Do not write log statements below this threshold to the file.
    threshold: ALL
    
    # The file to which current statements will be logged.
    currentLogFilename: ./logs/library.log
    
    # When the log file rotates, the archived log will be renamed to this and gzipped. The
    # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
    # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
    archivedLogFilenamePattern: ./logs/library-%d.log.gz
    
    # The number of archived files to keep.
    archivedFileCount: 5

    # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
    timeZone: UTC